# Generated by Django 2.2.5 on 2019-09-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=28)),
                ('patente', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=9)),
                ('estacionamiento', models.CharField(max_length=10)),
                ('deptoAsociado', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('rut', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=28)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
