# Generated by Django 2.2.5 on 2019-09-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190909_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovehiculos',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
