# Generated by Django 2.2.5 on 2019-09-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190909_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovehiculos',
            name='day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registrovehiculos',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registrovehiculos',
            name='vehiculo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registrovehiculos',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
