# Generated by Django 2.2.5 on 2019-10-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191012_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovehiculos',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
