# Generated by Django 2.2.5 on 2019-11-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registrovehiculos_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovehiculos',
            name='registrado',
            field=models.BooleanField(default=False),
        ),
    ]
