# Generated by Django 2.2.5 on 2019-11-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_registrovehiculos_registrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovehiculos',
            name='entrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrovehiculos',
            name='patente',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='registrovehiculos',
            name='salida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrovehiculos',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patentes.Vehiculo'),
        ),
    ]
