# Generated by Django 2.2.2 on 2019-06-05 03:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=28)),
                ('patente', models.CharField(max_length=6)),
                ('estacionamiento', models.CharField(max_length=10)),
                ('deptoAsociado', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('rut', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=28)),
                ('telefono', models.CharField(max_length=12)),
            ],
            managers=[
                ('vehiculos', django.db.models.manager.Manager()),
            ],
        ),
    ]
