# Generated by Django 2.2.5 on 2019-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patentes', '0002_auto_20190610_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(default='Residente', max_length=9),
            preserve_default=False,
        ),
    ]
