# Generated by Django 2.2.5 on 2019-09-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patentes', '0003_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Residente', 'Residente'), ('Visita', 'Visita'), ('Servicios', 'Servicios')], default='Residente', max_length=9),
        ),
    ]
